# Generated by Django 3.2.5 on 2021-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_user_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_statement',
            field=models.CharField(blank=True, max_length=1250),
        ),
    ]
