# Generated by Django 3.2.5 on 2021-11-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211126_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
