# Generated by Django 3.2.8 on 2021-12-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_user_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
    ]
