# Generated by Django 3.2.8 on 2021-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_club_mission_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
