# Generated by Django 3.2.5 on 2021-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20211209_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_location',
        ),
    ]
