# Generated by Django 3.2.5 on 2021-12-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_remove_club_club_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='member_count',
        ),
    ]
