# Generated by Django 3.2.5 on 2021-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_remove_club_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
