# Generated by Django 3.2.8 on 2021-12-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_club_location'),
        ('clubs', '0014_alter_club_club_location'),
    ]

    operations = [
    ]
