# Generated by Django 3.2.8 on 2021-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_merge_20211210_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='location',
        ),
        migrations.AlterField(
            model_name='club',
            name='club_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
