# Generated by Django 3.2.8 on 2021-12-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_auto_20211210_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
