# Generated by Django 3.2.5 on 2021-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
