# Generated by Django 3.2.5 on 2021-12-12 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_club_club_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
